#!/bin/sh
mkdir -p "./mysearch/result01"

if [ -f "/Users/oliverehmer/Desktop/act_examplecorpus/gat/ARG_I_PAR_Maria.wav" ]
then
 ffmpeg -i "/Users/oliverehmer/Desktop/act_examplecorpus/gat/ARG_I_PAR_Maria.wav" -ss 7.37405797516546 -t 1.82561527932214 -y "./mysearch/result01/result01.wav" -hide_banner
fi


mkdir -p "./mysearch/result02"

if [ -f "/Users/oliverehmer/Desktop/act_examplecorpus/gat/ARG_I_PER_Alejo.wav" ]
then
 ffmpeg -i "/Users/oliverehmer/Desktop/act_examplecorpus/gat/ARG_I_PER_Alejo.wav" -ss 8.18721416936325 -t 3.5920584100245 -y "./mysearch/result02/result02.wav" -hide_banner
fi


mkdir -p "./mysearch/result03"

if [ -f "/Users/oliverehmer/Desktop/act_examplecorpus/gat/ARG_I_PER_Alejo.wav" ]
then
 ffmpeg -i "/Users/oliverehmer/Desktop/act_examplecorpus/gat/ARG_I_PER_Alejo.wav" -ss 8.18721416936325 -t 3.5920584100245 -y "./mysearch/result03/result03.wav" -hide_banner
fi


mkdir -p "./mysearch/result04"

if [ -f "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_CBBA_SoniaYJanette.wav" ]
then
 ffmpeg -i "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_CBBA_SoniaYJanette.wav" -ss 1.24171465085766 -t 1.71209940094861 -y "./mysearch/result04/result04.wav" -hide_banner
fi


mkdir -p "./mysearch/result05"

if [ -f "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_CBBA_SoniaYJanette.wav" ]
then
 ffmpeg -i "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_CBBA_SoniaYJanette.wav" -ss 8.48610236407555 -t 2.58389575557725 -y "./mysearch/result05/result05.wav" -hide_banner
fi


mkdir -p "./mysearch/result06"

if [ -f "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_CBBA_SoniaYJanette.wav" ]
then
 ffmpeg -i "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_CBBA_SoniaYJanette.wav" -ss 33.1720732777843 -t 2.7270631192024 -y "./mysearch/result06/result06.wav" -hide_banner
fi


mkdir -p "./mysearch/result07"

if [ -f "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_CBBA_SoniaYJanette.wav" ]
then
 ffmpeg -i "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_CBBA_SoniaYJanette.wav" -ss 74.4116982688152 -t 1.3985257119878 -y "./mysearch/result07/result07.wav" -hide_banner
fi


mkdir -p "./mysearch/result08"

if [ -f "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_CCBA_Botellita.wav" ]
then
 ffmpeg -i "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_CCBA_Botellita.wav" -ss 4.09201741627458 -t 0.591242409655155 -y "./mysearch/result08/result08.wav" -hide_banner
fi


mkdir -p "./mysearch/result09"

if [ -f "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_CCBA_SP_MeryGaby2.wav" ]
then
 ffmpeg -i "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_CCBA_SP_MeryGaby2.wav" -ss 3.1109574603326 -t 2.87371374022612 -y "./mysearch/result09/result09.wav" -hide_banner
fi


mkdir -p "./mysearch/result10"

if [ -f "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_CCBA_SP_MeryGaby2.wav" ]
then
 ffmpeg -i "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_CCBA_SP_MeryGaby2.wav" -ss 3.1109574603326 -t 2.87371374022612 -y "./mysearch/result10/result10.wav" -hide_banner
fi


mkdir -p "./mysearch/result11"

if [ -f "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_PD_Ruido.wav" ]
then
 ffmpeg -i "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_PD_Ruido.wav" -ss 0.196561783058115 -t 2.50249556450019 -y "./mysearch/result11/result11.wav" -hide_banner
fi


mkdir -p "./mysearch/result12"

if [ -f "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_RADIO_CCBA_SenoraIndignada.wav" ]
then
 ffmpeg -i "/Users/oliverehmer/Desktop/act_examplecorpus/gat/BOL_RADIO_CCBA_SenoraIndignada.wav" -ss 11.8523250398267 -t 3.16596476481728 -y "./mysearch/result12/result12.wav" -hide_banner
fi


