.emptyAnnotations <- data.frame(
	annotationID 			= as.integer(),
	tierName 				= as.character(),
	startsec 				= as.double(),
	endsec 					= as.double(),
	content 				= as.character(),
	content.norm 			= as.character(),
	char.orig.bytime.start 	= as.integer(),
	char.orig.bytime.end	= as.integer(),
	char.norm.bytime.start	= as.integer(),
	char.norm.bytime.end	= as.integer(),
	char.orig.bytier.start 	= as.integer(),
	char.orig.bytier.end 	= as.integer(),
	char.norm.bytier.start 	= as.integer(),
	char.norm.bytier.end 	= as.integer(),
	row.names 				= as.character(), 
	stringsAsFactors        = FALSE)

.emptyAnnotations$annotationID	<- as.integer(.emptyAnnotations$annotationID)
.emptyAnnotations$startsec		<- as.double(.emptyAnnotations$startsec)
.emptyAnnotations$endsec  		<- as.double(.emptyAnnotations$endsec)
.emptyAnnotations$content  		<- as.character(.emptyAnnotations$content)

.emptyTiers <- data.frame(
	name 				= as.character(),
	type 				= as.character(),
	position 			= as.integer(),
	stringsAsFactors 	= FALSE)

.emptyMedia <- data.frame(
	path 				= as.character(),
	source.path 		= as.character(),
	clip.id 			= as.character(),
	startsec 			= as.double(),
	startsec.source 	= as.character(),
	length.sec 			= as.double(),
	video.width 		= as.integer(),
	video.height 		= as.integer(),
	video.fps 			= as.double(),
	video.codec 		= as.character(),
	video.bitrate 		= as.double(),
	audio.sample.rate 	= as.integer(),
	audio.channels 		= as.integer(),
	audio.codec 		= as.character(),
	audio.bitrate 		= as.double(),
	container.format 	= as.character(),
	file.size 			= as.double(),
	volume.kind 		= as.character(),
	volume.name 		= as.character(),
	kind 				= as.character(),
	type 				= as.character(),
	stringsAsFactors 	= FALSE)

#' transcript object
#' 
#' A transcript object contains the annotations of a loaded annotation file and some meta data .
#' In addition, it contains information that is auto generated by the act package, which is necessary for some functions (e.g. the full text search) 
#' 
#' Some of the slots are defined by the user.
#' Other slots are \code{[READ ONLY]}, which means that they can be accessed by the user but 
#' should not be changed. They contain values that are filled when you execute functions 
#' on the object.
#' 
#' @slot name Character string; \code{[READ ONLY]} Name of the transcript, generated from the annotation file name.
#' @slot file.path Character string; \code{[READ ONLY]} Original location of the annotation file.
#' @slot file.encoding Character string; \code{[READ ONLY]} Encoding applied to the file when reading.
#' @slot file.type Character string; \code{[READ ONLY]} Type of the original annotation file/object, e.g. 'eaf' or 'textgrid' for files and 'rpraat' for a rPraat .TextGrid object.
#' @slot file.content Character string; \code{[READ ONLY]} Content of the original annotation file/object.
#' @slot import.result Character string; \code{[READ ONLY]} Information about the success of the import of the annotation file.
#' @slot load.message Character string; \code{[READ ONLY]} Possibly messages about errors that occurred on importing the annotation file.
#' @slot length.sec Double; \code{[READ ONLY]} Duration of the transcript in seconds.
#' @slot tiers Data.frame; \code{[READ ONLY]} Table with the tiers. To modify the tiers it is highly recommended to use functions of the package to ensure for consistency of the data.
#' @slot annotations Data.frame; Table with the annotations.
#' @slot media Data.frame; Table of the media files that correspond to this transcript object. Core columns: \code{path} (absolute file path), \code{source.path} (path of the source recording a clip was cut from), \code{clip.id} (clip identifier), \code{startsec} (start of the file in the original time reference, 0 for full recordings), \code{startsec.source} (where startsec came from: "tag"/"timecode"/"corpus"), \code{length.sec} (file duration), \code{video.width}, \code{video.height}, \code{video.fps}, \code{video.codec}, \code{video.bitrate}, \code{audio.sample.rate}, \code{audio.channels}, \code{audio.codec}, \code{audio.bitrate}, \code{container.format}, \code{file.size} (bytes), \code{kind} ("full" or "clip"), \code{type} ("video" or "audio"). Columns that are not yet read may be \code{NA}. Additional columns may be present.
#' @slot normalization.signature Character string; \code{[READ ONLY]} Hash signature of the inputs that produced the current normalization (annotations content + normalization matrix). Used to detect when re-normalization is needed.
#' @slot fulltext.signature Character string; \code{[READ ONLY]} Hash signature of the inputs that produced the current fulltexts (annotations + separators + tier filter). Used to detect when re-creation of the fulltexts is needed.
#' @slot fulltext.filter.tier.names Vector of character strings; names of tiers that were included in the full text..
#' @slot fulltext.bytime.orig Character string; \code{[READ ONLY]} full text of the transcript based on the ORIGINAL content of the annotations, sorting the annotations by TIME
#' @slot fulltext.bytime.norm Character string; \code{[READ ONLY]} full text of the transcript based on the NORMALIZED content of the annotations, sorting the annotations by TIME
#' @slot fulltext.bytier.orig Character string; \code{[READ ONLY]} full text of the transcript based on the ORIGINAL content of the annotations, sorting the annotations first by TIERS and then by time
#' @slot fulltext.bytier.norm Character string; \code{[READ ONLY]} full text of the transcript based on the NORMALIZED content of the annotations, sorting the annotations first by TIERS and then by time
#' @slot history List; \code{[READ ONLY]} History of the modifications made to the transcript object.
#' @export
#'
#' @examples 
#' library(act)
#' 
#' examplecorpus@transcripts[[1]]
#' 
methods::setClass("transcript", 
				  representation(
				  	name                       = "character",
				  	file.path                  = "character",
				  	file.encoding              = "character",
				  	file.type                  = "character",
				  	file.content               = "ANY",
				  	
				  	import.result                = "character",
				  	load.message               = "character",
				  	
				  	length.sec                 = "numeric",
				  	tiers                      = "ANY",
				  	annotations                = "ANY",
				  	media                      = "data.frame",

				  	normalization.signature    = "character",
				  	fulltext.signature         = "character",
				  	fulltext.filter.tier.names = "character",
				  	fulltext.bytime.orig       = "character",
				  	fulltext.bytime.norm       = "character",
				  	fulltext.bytier.orig       = "character",
				  	fulltext.bytier.norm       = "character",
				  	history                    = "list"
				  	
				  ), prototype = list (
				  	name                       = "",
				  	file.path                  = "",
				  	file.encoding              = "",
				  	file.type                  = "",
				  	file.content               = character(),
				  	
				  	import.result                = "",
				  	load.message               = "",
				  	
				  	length.sec                 = 0,
				  	tiers                      = .emptyTiers,
				  	annotations                = .emptyAnnotations ,
				  	media                      = .emptyMedia,

				  	normalization.signature    = character(),
				  	fulltext.signature         = character(),
				  	fulltext.filter.tier.names = character(),
				  	fulltext.bytime.orig       = "",
				  	fulltext.bytime.norm       = "",
				  	fulltext.bytier.orig       = "",
				  	fulltext.bytier.norm       = "",
				  	history           = list()
				  )
)

transcript_show <- function (object) {
	w <- 26
	.show_title(paste0("transcript object: ", object@name))

	.show_head("General")
	.show_dl(c(
		"length.sec"  = as.character(object@length.sec),
		"tiers"       = as.character(nrow(object@tiers)),
		"annotations" = as.character(nrow(object@annotations))
	), width = w)

	.show_sep()
	.show_head("File")
	.show_dl(c(
		"file.path"     = object@file.path,
		"file.encoding" = object@file.encoding,
		"file.type"     = object@file.type,
		"file.content"  = if(length(object@file.content)==0) "[empty]" else "[check directly]"
	), width = w)

	.show_sep()
	.show_head("Import")
	.show_dl(c(
		"import.result" = object@import.result,
		"load.message"  = object@load.message,
		"media"         = if(nrow(object@media)==0) "[empty]" else paste("[check directly]", nrow(object@media), "file(s)")
	), width = w)

	.show_sep()
	.show_head("Processing")
	.show_dl(c(
		"normalized"                 = if (length(object@normalization.signature) > 0) "yes" else "no",
		"fulltext"                   = if (length(object@fulltext.signature) > 0) "yes" else "no",
		"fulltext.filter.tier.names" = paste(length(object@fulltext.filter.tier.names), "name(s)"),
		"history"                    = paste(length(object@history), "message(s)")
	), width = w)

	.show_sep()
	info <- act::info_summarized(object)
	.show_head("Summary")
	.show_dl(c(
		"tier.count"       = as.character(info$tier.count),
		"annotations.count" = as.character(info$annotations.count),
		"words.org.count"  = as.character(info$words.org.count),
		"words.norm.count" = as.character(info$words.norm.count)
	), width = w)
}

methods::setMethod("show", signature = "transcript", definition = transcript_show)


