#' Create cut lists for 'FFmpeg' 
#' 
#' This function creates FFmpeg commands to cut media files for each search results.
#' If you want to execute the commands (and cut the media files) you need to have FFmpeg installed on you computer. To install FFmpeg you can follow the instructions given in the vignette 'installation-ffmpeg'. Show the vignette with \code{vignette("installation-ffmpeg")}.
#' 
#' \emph{Cut lists}\cr
#' The commands are collected in cut lists. 
#' The cut lists will be stored in different ways:
#' * A cut list for for ALL search results will be stored in \code{s@cuts.cutlist.mac} to be used on MacOS and \code{s@cuts.cutlist.win} to be used on Windows.
#' * Individual cut lists for EACH search result will be stored in additional columns in the data frame \code{s@results}.
#' The cut lists that can be executed in the Terminal (Apple) or the Command Line Interface (Windows). 
#'  
#' \emph{Input media files}\cr
#' The function will use all files in  \code{corpus@transcripts[[ ]]@media}.
#' Therefore you will need to set the options \code{filterMediaInclude} filtering for which input media files you want to create the cuts.
#' The filter is a regular expression, e.g.  \code{'\\.(wav|aif)'} for '.wav' and '.aif' audio files or \code{'\\.mp4'} for '.mp4' video files.
#'
#' \emph{Output file names}\cr
#' The file names of the cuts are taken from the \code{resultID} column in the search results table. To change this, modify the contents of this column or define a different column using \code{options(act.export.filename.fromColumnName}. 
#' By default, the device descriptor of the original media will be appended to the file name. It is taken from the \code{devices} column of \code{corpus@transcripts[[ ]]@media}. To change this, modify that column.
#' 
#' \emph{Output format}\cr
#' The output format is predefined by in the options:
#' * \code{act.ffmpeg.command.video}: FFmpeg command for video cuts
#' * \code{act.ffmpeg.command.audio}: FFmpeg command for audio cuts (default: codec copy)
#' * \code{act.ffmpeg.command.audio.mp3}: FFmpeg command for converting audio to MP3
#' * \code{act.ffmpeg.command.images}: FFmpeg command for extracting still images
#'  
#'  
#' \emph{Extract stills}\cr
#' To extract stills the time information and the file names need to be stored in the search object in the results data frame, e.g. in \code{s@results}.
#' The information needs to be contained in a vector.
#' The elements of the vector are the time values in seconds, the name attribute will be used as file name, e.g. \code{myStills <- c(still1=1.0, still2=2.0)}.
#' The vector needs stored for each search result in the column called \code{stills.values} as a list, e.g code \code{s@results$stills.values[[1]] <- myStills}.
#' Stills will be stored in a sub folder called \code{stills} by default, if not otherwise defined in the column \code{stills.folder}. 
#' Please see the section \code{options_show} to customize the behavior of the function.
#'  
#'  
#' \emph{Advanced options}\cr
#' You can adjust the FFmpeg commands according to your needs.
#' The following options define the FFmpeg command that will be used by the package. The command needs to contain place holders which will be replaced by the actual values in the package. If you want to define your own ffmpeg command, please make sure to use the following placeholders:
#' * \code{INPUTARGS} the input + seek arguments, generated by act based
#'   on the media type and \code{videoFastPositioning}. Replaces the
#'   previous \code{INFILEPATH} + \code{TIMESTART}/\code{TIMEDURATION}
#'   placeholders. Contains an \code{INFILEPATH} sub-placeholder that is
#'   replaced by act with the actual input file path.
#' * \code{OUTFILEPATH} path where the output media file will be saved
#' * \code{OPTIONS} FFmpeg options that will be applied additionally, in particular pan/channel args.
#'   
#' @md
#' 
#' @param x Corpus object; Please note: all media paths for a transcript need to be given as a list in the corpus object in \code{corpus@transcripts[[ ]]@media} . You can use the respective media functions. . 
#' @param s Search object.
#' @param exportMedia Logical; If \code{TRUE} media cuts (audio/video)  will be included in the cut list.
#' @param exportStills Logical; If \code{TRUE} stills (image) will be included in the cut list. For creating the list of stills to be exported see \link{search_cuts_media}.
#' @param exportThumbnail Logical; If \code{TRUE} a thumbnail image (.jpg) will be exported to the main folder. The name will be the same as the media cut. By default the time value is the start of the search hit. To change this set time values in seconds in a column called \code{thumbnails} in \code{s@results}. 
#' @param cutSpanBeforesec Double; Start the media cut some seconds before the hit to include some context; the default \code{NULL} will take the value as set in @cuts.span.beforesec of the search object.
#' @param cutSpanAftersec Double; End the media cut some seconds before the hit to include some context; the default \code{NULL} will take the value as set in @cuts.span.beforesec of the search object.
#' @param folderOutput Character string; path to folder where files will be written.
#' @param filterMediaInclude Character string; regular expression to match only some of the media files in \code{corpus@transcripts[[ ]]@media}.
#' @param filterMediaExclude Character string; regular expression to exclude some of the media files in \code{corpus@transcripts[[ ]]@media}. Empty string (default) excludes none.
#' @param videoFastPositioning Logical; If \code{TRUE} the input args use double \code{-ss} for fast frame-accurate seeking (slow decode only over the last few seconds). If \code{FALSE} a single \code{-ss} after \code{-i} is used (full decode). Only affects video cuts and still extraction; audio cuts always use the slow form.
#' @param videoCodecCopy Logical; If \code{TRUE} FFMPEG will use the option *codec copy* for videos.
#' @param audioAsMP3 Logical; If \code{TRUE} audio cuts will be converted to .mp3 files using \code{options()$act.ffmpeg.command.audio.mp3}. If \code{FALSE} (default) audio format is preserved using \code{options()$act.ffmpeg.command.audio}.
#' @param audioPanning Integer; 0=leave audio as is (ch1&ch2) , 1=only channel 1 (ch1), 2=only channel 2 (ch2), 3=both channels separated (ch1&ch2), 4=all three versions (ch1&ch2, ch1, ch2). This setting will override the option made in 'act.ffmpeg.channels_from_column' .
#' @param audioNormalize Logical; If \code{TRUE} and option \code{act.ffmpeg.audio.loudnorm} is set, a loudnorm filter is appended to the audio filter chain. Default is \code{FALSE}.
#' @param outputOS Vector of character Strings; Saves FFMpeg cut list in format for \code{"win"}=windows, \code{"mac"}=apple ox/linux.
#' @param outputFileName Character String; Name of the cut list.
#' 
#' @return Search object; cut lists will be stored in \code{s@cuts.cutlist.mac} and \code{s@cuts.cutlist.win}.
#'
#' @seealso \link{search_cuts_media}, \code{vignette("install_ffmpeg", package = "act")}
#' 
#' @export
#'
#' @example inst/examples/search_cuts_media.R
#' 
search_cuts_media <- function(x,
							  s,
							  exportMedia          = TRUE,
							  exportStills         = TRUE,
							  exportThumbnail      = TRUE,
							  cutSpanBeforesec     = NULL,
							  cutSpanAftersec      = NULL,
							  folderOutput         = NULL,
							  filterMediaInclude   = "",
							  filterMediaExclude   = "",
							  videoFastPositioning = TRUE,
							  videoCodecCopy       = FALSE,
							  audioAsMP3           = FALSE,
							  audioPanning         = NULL,
							  audioNormalize       = FALSE,
							  outputOS             = c("mac", "win"),
							  outputFileName       = "FFMPEG_cutlist")
{
	if (1==2) {
#		x                    <- corpus
#		s                    <- s
#		exportMedia          <- TRUE
#		exportStills         <- TRUE
#		exportThumbnail      <- TRUE
#		cutSpanBeforesec     <- NULL
#		cutSpanAftersec      <- NULL
#		folderOutput         <- ""
#		filterMediaInclude   <- ""
#		videoFastPositioning <- TRUE
#		videoCodecCopy       <- FALSE
#		audioAsMP3           <- FALSE
#		audioPanning         <- NULL
#		audioNormalize       <- FALSE
#		exportStills         <- TRUE
	}
	
	#==== CHECKS ====
	.assert_corpus(x, missing = missing(x))
	.assert_search(s, missing = missing(s))
	if (is.null(s@results$transcriptName))       	{ cli::cli_abort("Data frame s@results does not contain column {.arg transcriptName}.") 	}
	if (nrow(s@results)==0) 	                    { cli::cli_abort("Data frame s@results does not contain any search results (data frame with 0 rows)") 	}
	if (!is.null(folderOutput)) {
		if (!options()$act.export.filename.fromColumnName %in% colnames(s@results)) {
			cli::cli_abort("The column defined in the option 'options()$act.export.filename.fromColumnName' does not exist in the data.frame with the search results.")
		}
	}
	if (!is.null(cutSpanBeforesec)) 	{
		if (length(cutSpanBeforesec)!=1) {
			cli::cli_abort("Parameter {.arg cutSpanBeforesec} needs to contain only one element as a numeric value.")
		}
		if (!is.numeric(cutSpanBeforesec)) {
			cli::cli_abort("Parameter {.arg cutSpanBeforesec} needs to be a numeric value.")
		}
		s@cuts.span.beforesec       <- cutSpanBeforesec
	}
	if (!is.null(cutSpanAftersec)) 	{
		if (length(cutSpanAftersec)!=1) {
			cli::cli_abort("Parameter {.arg cutSpanAftersec} needs to contain only one element as a numeric value.")
		}
		if (!is.numeric(cutSpanAftersec)) {
			cli::cli_abort("Parameter {.arg cutSpanAftersec} needs to be a numeric value.")
		}
		s@cuts.span.aftersec       <- cutSpanAftersec
	}
	
	#stills.values:	check if column exists
	if (exportStills) {
		if (!"stills.values" %in% colnames(s@results)) {
			cli::cli_abort("The results data frame of your search object does not contain a column called {.val stills.values}.")
		}
	} 
	
	#==== VARIABLES ====
	myWarnings <- c()
	#---- . out folder ----
	#if cut list should be saved : set output folder
	if (is.null(folderOutput)) {
		out_folder_main <- "."
	} else {
		out_folder_main <- normalizePath(folderOutput, winslash = "/", mustWork = FALSE)
	}
	
	#---- . total cut lists ----
	mac_cutlist <- c()
	win_cutlist <- c()
	
	#---- . file names ---- 
	#add name of result and file type
	#name of sequence : sub folder for each search result
	filename.fromColumnName <- options()$act.export.filename.fromColumnName
	if(!filename.fromColumnName %in% colnames(s@results)) {
		filename.fromColumnName <- "resultID" 				
	}
	
	#==== MAIN LOOP: each search results ====
	#set progress bar
	helper_progress_set("Creating cutlist", max(1,nrow(s@results)))
	#initialize hiere (otherwise there will be an error if no media files at all are found)
	win_video <- c()
	mac_video <- c()

	fps_cache <- list()

	res<-1
	for (res in 1:nrow(s@results)) 	{
		#update progress bar
		helper_progress_tick()
		
		#---- . variables ----
		mac_cutlist <- c(mac_cutlist, paste0("#====  ", as.character(s@results[res, filename.fromColumnName])))
		cmd_titletext   <- stringr::str_flatten(c(s@results[res, filename.fromColumnName], " (", res, " of ", nrow(s@results)," search results)"), collapse="")
		
		#---- . folder ----
		#from main folder
		out_folder_current <- out_folder_main
		if (s@name!="") 	{ out_folder_current <- file.path(out_folder_current, s@name)	}
		
		#via folder grouping 1: default=by resultID
		foldergrouping.fromColumnName <- options()$act.export.folder.grouping1.fromColumnName
		if (foldergrouping.fromColumnName!="") {
			if(foldergrouping.fromColumnName %in% colnames(s@results)) {
			} else {
				foldergrouping.fromColumnName <- "resultID"
			}
			foldername <- as.character(s@results[res, foldergrouping.fromColumnName])
			if(!is.na(foldername)) {
				if(!length(foldername)==0) {
					if (foldername!="") {
						out_folder_current <- file.path(out_folder_current, foldername)
					}
				}
			}
		}
		
		#---- . paths media ----
		t <- NULL
		if (is.null(s@results$transcriptName[res])) {
			#transcript not found
			myWarnings <- c(myWarnings, sprintf("result %s '%s': transcript '%s' not found in corpus", res, as.character(s@results[res, options()$act.export.filename.fromColumnName]), as.character(s@results$transcriptName[res])))
		} else {
			t <- x@transcripts[[ s@results$transcriptName[res] ]]
			if (is.null(t)) {
				#transcript not found
				myWarnings <- c(myWarnings, sprintf("result %s '%s': transcript '%s' not found in corpus", res, as.character(s@results[res, options()$act.export.filename.fromColumnName]), as.character(s@results$transcriptName[res])))
			}
		}
		if (is.null(t)) {
			next
		}
		
		#==== SUB LOOP: each media file ====
		#get paths
		in_paths <- t@media$path
		#devices descriptor used as filename suffix; fall back to base name when absent
		if ("devices" %in% colnames(t@media)) {
			in_descriptors <- t@media$devices
		} else {
			in_descriptors <- stringr::str_to_lower(tools::file_path_sans_ext(basename(in_paths)))
		}
		if (!filterMediaInclude=="") {
			keep           <- grep(pattern=filterMediaInclude, in_paths)
			in_paths       <- in_paths[keep]
			in_descriptors <- in_descriptors[keep]
		}
		if (!filterMediaExclude=="") {
			keep           <- !grepl(pattern=filterMediaExclude, in_paths)
			in_paths       <- in_paths[keep]
			in_descriptors <- in_descriptors[keep]
		}

		#if no media path found: default name
		if (length(in_paths)==0) {
			in_paths       <- "DEFAULT_MEDIA_PATH"
			in_descriptors <- ""
		}
		j<-1
		for (j in 1:length(in_paths)) {
			#skip if path is NA
			if (is.na(in_paths[j])) {next}
			
			mac_cutlist <- c(mac_cutlist, paste0("#----  ", basename(in_paths[j])))
			
			#suffix of input media file
			in_suffix <- stringr::str_to_lower(tools::file_ext(in_paths[j]))
	
			if (in_suffix =="") {
				in_suffix <- "mp4"
			}
			
			#==== INFILEPATH ====
			mac_infilepath <- sprintf('PATH_INPUT="%s"', in_paths[j])
			mac_cutlist <- c(mac_cutlist, mac_infilepath)
			win_infilepath <- sprintf('SET "PATH_INPUT=%s"', in_paths[j])
			win_cutlist <- c(win_cutlist, win_infilepath)
			
			#==== MEDIA ====
			if (exportMedia) {
				#reset individual lists
				win_video <- c()
				mac_video <- c("#.... video")
				out_folder_video <- rep(out_folder_current, 3)
				
				#panned versions: group in folders by channels
				#if  CreatePannedVersions in the arguments if the functions is not set
				CreatePannedVersions <- 0
				if (!is.null(audioPanning)) {
					CreatePannedVersions <- audioPanning
				} else {
					#check if channels are set in the search results
					if(options()$act.ffmpeg.channels_from_column %in% colnames(s@results)) {
						#if it is set, take the value given there
						CreatePannedVersions <- s@results[res, options()$act.ffmpeg.channels_from_column]
						if (is.na(CreatePannedVersions)) {
							CreatePannedVersions <-0
						}
					}
				}
				
				if (CreatePannedVersions==0 ) {			#no panning
					#
				} else if (CreatePannedVersions==1 ) {	#only left
					#
				} else if (CreatePannedVersions==2 ) {	#only right
					#
				} else if (CreatePannedVersions==3)  {	#left and right
					out_folder_video[2] <- file.path(out_folder_video[2], "ch1")
					out_folder_video[3] <- file.path(out_folder_video[3], "ch2")
				} else if (CreatePannedVersions==4 ) {	#all three versions
					out_folder_video[1] <- file.path(out_folder_video[1], "ch1_ch2")
					out_folder_video[2] <- file.path(out_folder_video[2], "ch1")
					out_folder_video[3] <- file.path(out_folder_video[3], "ch2")
				}
				
				#---- . folder grouping 2 ----
				#subfolder for each cut
				foldergrouping.fromColumnName <- options()$act.export.folder.grouping2.fromColumnName
				if (foldergrouping.fromColumnName!="") {
					if(foldergrouping.fromColumnName %in% colnames(s@results)) {
						foldername <- as.character(s@results[res, foldergrouping.fromColumnName])
						if(!is.na(foldername)) {
							if(!length(foldername)==0) {
								if (foldername!="") {
									out_folder_video <- file.path(out_folder_video, foldername)
								}
							}
						}
					} 
				}
				
				#---- . directory commands ----
				out_folder_video_all <- c()
				if (CreatePannedVersions==0) { out_folder_video_all <- c(out_folder_video_all, out_folder_video[1])	  }
				if (CreatePannedVersions==1) { out_folder_video_all <- c(out_folder_video_all, out_folder_video[2])	  }
				if (CreatePannedVersions==2) { out_folder_video_all <- c(out_folder_video_all, out_folder_video[3])	  }
				if (CreatePannedVersions==3) { out_folder_video_all <- c(out_folder_video_all, out_folder_video[2:3]) }
				if (CreatePannedVersions==4) { out_folder_video_all <- c(out_folder_video_all, out_folder_video[1:3]) }
				
				out_folder_video_all <- unique(out_folder_video_all)
				if (length(out_folder_video_all)>0) {
					win_makedir  <- stringr::str_flatten(sprintf('IF NOT EXIST "%s" ( md "%s" )', out_folder_video_all, out_folder_video_all), collapse='\n')
					win_video <- c(win_video, win_makedir)
					mac_makedir  <- stringr::str_flatten(sprintf('mkdir -p "%s"', out_folder_video_all), collapse='\n')
					mac_video <- c(mac_video, mac_makedir)
				}
				
				#get format / suffix of input media file
				out_suffix <- in_suffix
				
				#set standard command based on media type
				is_video_file <- in_suffix %in% options()$act.media.fileformats.video
				is_audio_file <- in_suffix %in% options()$act.media.fileformats.audio
				if (is_audio_file) {
					cmd <- options()$act.ffmpeg.command.audio
				} else {
					cmd <- options()$act.ffmpeg.command.video
				}

				#if it is an audio file and should be converted to mp3
				if (is_audio_file & audioAsMP3) {
					cmd <- options()$act.ffmpeg.command.audio.mp3
					#replace destination file extension with mp3
					out_suffix <- "mp3"
				}
				
				#---- . out paths ----
				out_filePath <- rep("",3)
				filename <- as.character(s@results[res, filename.fromColumnName])
				#append media name to file name if there is more than one media file
				if(length(in_paths)>1) {
					if (!is.na(in_descriptors[j]) && in_descriptors[j]!="") {filename = paste0(filename, "__", in_descriptors[j])}
				}
				
				#replace everything that is not allowed in file names
				filename <- stringr::str_replace_all(filename, "[^\\p{L}\\p{N}_\\.-]", "_")
				
				out_filePath[1] <- file.path(out_folder_video[1], paste(filename, ".",     out_suffix, sep=""))
				out_filePath[2] <- file.path(out_folder_video[2], paste(filename, "_ch1.", out_suffix, sep=""))
				out_filePath[3] <- file.path(out_folder_video[3], paste(filename, "_ch2.", out_suffix, sep=""))
				
				#---- . command replacements ----
				startsec 	<- max(0, s@results$startsec[res] - s@cuts.span.beforesec)
				endsec 		<- min(s@results$endsec[res] + s@cuts.span.aftersec, t@length.sec)
				duration <- endsec - startsec
				if (is_video_file && isTRUE(videoFastPositioning)) {
					inputargs <- sprintf('-ignore_editlist 1 -avoid_negative_ts make_zero -ss %s -i "INFILEPATH" -ss 10.000 -t %s',
					                     as.character(max(0, startsec - 10)),
					                     as.character(duration))
				} else {
					inputargs <- sprintf('-ignore_editlist 1 -avoid_negative_ts make_zero -i "INFILEPATH" -ss %s -t %s',
					                     as.character(startsec),
					                     as.character(duration))
				}
				cmd <- .ffmpeg_apply_path(cmd)
				cmd <- stringi::stri_replace_all_fixed(cmd, "INPUTARGS", inputargs)
				if (tolower(out_suffix) %in% c("mp4", "mov", "m4a", "m4v")) {
					cmd <- stringi::stri_replace_all_fixed(
						cmd, '-y "OUTFILEPATH"',
						'-use_editlist 0 -movflags +faststart -y "OUTFILEPATH"')
				}

				fps_for_meta <- NULL
				if (is_video_file) {
					if (is.null(fps_cache[[in_paths[j]]])) {
						fps_cache[[in_paths[j]]] <- .metadata_probe_fps(in_paths[j])
					}
					fps_for_meta <- fps_cache[[in_paths[j]]]
				}
				meta_argv <- helper_metadata_ffmpeg_argv(
					sourcePath = in_paths[j],
					startsec   = s@results$startsec[res],
					clipID     = filename,
					fps        = fps_for_meta
				)

				#panning + normalization versions
				cmd <- rep(cmd, 3)
				loudnorm_str <- if (isTRUE(audioNormalize)) getOption("act.ffmpeg.audio.loudnorm") else NULL
				cv_str       <- if (isTRUE(videoCodecCopy)) "-c:v copy" else ""
				opts_1 <- .search_cuts_build_options(pan = NULL,           loudnorm = loudnorm_str, cv = cv_str)
				opts_2 <- .search_cuts_build_options(pan = "pan=1c|c0=c0", loudnorm = loudnorm_str, cv = cv_str)
				opts_3 <- .search_cuts_build_options(pan = "pan=1c|c0=c1", loudnorm = loudnorm_str, cv = cv_str)
				cmd[1] <- stringi::stri_replace_all_fixed(cmd[1], " OPTIONS ", opts_1)
				cmd[2] <- stringi::stri_replace_all_fixed(cmd[2], " OPTIONS ", opts_2)
				cmd[3] <- stringi::stri_replace_all_fixed(cmd[3], " OPTIONS ", opts_3)
				cmd[1] <- stringi::stri_replace_all_fixed(cmd[1], "OUTFILEPATH", out_filePath[1])
				cmd[2] <- stringi::stri_replace_all_fixed(cmd[2], "OUTFILEPATH", out_filePath[2])
				cmd[3] <- stringi::stri_replace_all_fixed(cmd[3], "OUTFILEPATH", out_filePath[3])


				win_cmd <- stringi::stri_replace_all_fixed(cmd, "INFILEPATH", "%PATH_INPUT%")
				mac_cmd <- stringi::stri_replace_all_fixed(cmd, "INFILEPATH", "$PATH_INPUT")

				if (length(meta_argv) > 0) {
					mac_meta <- paste(shQuote(meta_argv, type = "sh"), collapse = " ")
					win_meta <- paste(paste0('"', stringi::stri_replace_all_fixed(meta_argv, '"', '""'), '"'), collapse = " ")
					win_meta <- stringi::stri_replace_all_fixed(win_meta, "/", "\u0001")
					mac_cmd  <- stringi::stri_replace_first_fixed(mac_cmd, ' -y "', paste0(" ", mac_meta, ' -y "'))
					win_cmd  <- stringi::stri_replace_first_fixed(win_cmd, ' -y "', paste0(" ", win_meta, ' -y "'))
				}

				#---- . command compile ----
				#compile
				win_video <- c(win_video, makeVideoBlock("win", CreatePannedVersions, in_filePath=in_paths[j],  out_filename=as.character(s@results[res, filename.fromColumnName]), win_cmd, cmd_titletext))
				win_video <- stringr::str_flatten(win_video)
				win_video <- stringr::str_replace_all(win_video, "/", "\\\\")
				win_video <- stringi::stri_replace_all_fixed(win_video, "\u0001", "/")
				
				mac_video <- c(mac_video, makeVideoBlock("mac", CreatePannedVersions, in_filePath=in_paths[j],  out_filename=as.character(s@results[res, filename.fromColumnName]), mac_cmd, cmd_titletext))
				
				#---- . command add ----
				#to search
				s@results[res, "cuts.cutlist.mac"] <- stringr::str_flatten(mac_video, collapse="\n")
				s@results[res, "cuts.cutlist.win"] <- stringr::str_flatten(win_video, collapse="\n")
				#to total cutlist
				
				mac_cutlist <- c(mac_cutlist, mac_video)
				win_cutlist <- c(win_cutlist, win_video)
			}
			
			#===== THUMBNAIL  ====
			#extract thumbs (only if it is a video file)
			if (exportThumbnail & (in_suffix %in% options()$act.media.fileformats.video)) 	{
				#check if time is set or default time
				time <- NA
				if("thumbnails" %in% colnames(s@results))  {
					#skip if col is present but current value is NA
					if (!is.na(s@results$thumbnails[res])) {
						if (!as.character(s@results$thumbnails[res])=="") {
							time<-as.double(s@results$thumbnails[res])
						}
					}
				} else {
					time<- s@results$startsec[res]
				}
				if (!is.na(time)) {
					#path
					#file by default sequence name
					filename <- as.character(s@results[res, filename.fromColumnName])
					
					#append media name to file name if there is more than one media file
					if(length(in_paths)>1) {
						if (!is.na(in_descriptors[j]) && in_descriptors[j]!="") {filename = paste0(filename, "__", in_descriptors[j])}
					}
					#replace everything that is not allowed in file names
					filename <- stringr::str_replace_all(filename, "[^\\p{L}\\p{N}_\\.-]", "_")
					#add jpg suffix
					filename <- paste0(filename, ".jpg")
					#compile path
					out_filePath <- file.path(out_folder_current, filename)
					
					#get command
					cmd <- .ffmpeg_apply_path(options()$act.ffmpeg.command.images)
					if (isTRUE(videoFastPositioning)) {
						inputargs <- sprintf('-ignore_editlist 1 -avoid_negative_ts make_zero -ss %s -i "INFILEPATH" -ss 10.000', as.character(max(0, time - 10)))
					} else {
						inputargs <- sprintf('-ignore_editlist 1 -avoid_negative_ts make_zero -i "INFILEPATH" -ss %s', as.character(time))
					}
					cmd <- stringi::stri_replace_all_fixed(cmd, "INPUTARGS",   inputargs)
					cmd <- stringi::stri_replace_all_fixed(cmd, "OUTFILEPATH", out_filePath)
					win_cmd <- stringi::stri_replace_all_fixed(cmd, "INFILEPATH", "%PATH_INPUT%")
					mac_cmd <- stringi::stri_replace_all_fixed(cmd, "INFILEPATH", "$PATH_INPUT")
					#cmd
					
					#windows version thumb 
					#(flatten/ some replacements windows )
					win_info         <- c()
					win_makedir      <- sprintf('IF NOT EXIST "%s" ( md "%s" )', out_folder_current, out_folder_current)
					win_if_statement <- "\nIF EXIST \"%1$s\" ( \n %2$s\n)\n"
					win_if_statement <- sprintf(win_if_statement, "%PATH_INPUT%" ,win_cmd)
					win_thumbnail    <- c(win_info, win_makedir, win_if_statement)
					win_thumbnail    <- stringr::str_replace_all(win_thumbnail, "/", "\\\\")
					
					#mac version thumb
					mac_info         <- c("#.... thumbnail")
					mac_makedir      <- sprintf('mkdir -p "%s"', out_folder_current)
					mac_if_statement <- "\nif [ -f \"%1$s\" ]\nthen\n %2$s\nfi\n"
					mac_if_statement <- sprintf(mac_if_statement, "$PATH_INPUT" , mac_cmd)
					mac_thumbnail    <- c(mac_info, mac_makedir, mac_if_statement)
					
					#---- . command add ----
					#to search
					s@results[res, "cuts.thumbnail.mac"] <- stringr::str_flatten(mac_thumbnail, collapse="\n")
					s@results[res, "cuts.thumbnail.win"] <- stringr::str_flatten(win_thumbnail, collapse="\n")
					
					#to total cut list
					mac_cutlist <- c(mac_cutlist, mac_thumbnail)
					win_cutlist <- c(win_cutlist, win_thumbnail)
				}
			}
			
			#===== STILLS ====
			if (exportStills & (in_suffix %in% options()$act.media.fileformats.video)) {
				#values
				stills.values <- unlist(s@results$stills.values[[res]])
				if (!length(stills.values)==0) {
					
					#folder  
					out_folder_stills <- "stills"
					if ("stills.folder" %in% colnames(s@results)) {
						out_folder_stills <- s@results$stills.folder[res]
					} 
					out_folder_stills <- file.path(out_folder_current, out_folder_stills)
					
					#get names
					stills.names <- names(stills.values)
					#make sure times are double
					stills.values <- as.double(stills.values)
					#append media name to file name if there is more than one media file
					if(length(in_paths)>1) {
						if (!is.na(in_descriptors[j]) && in_descriptors[j]!="") {stills.names = paste0(stills.names, "__", in_descriptors[j])}
					}
					#replace everything that is not allowed in file names
					stills.names <- stringr::str_replace_all(stills.names, "[^\\p{L}\\p{N}_\\.-]", "_")
					#add jpg suffix
					stills.names <- paste0(stills.names, ".jpg")
					#compile path
					out_filePaths <- file.path(out_folder_stills, stills.names)
					
					#get command
					cmd <- .ffmpeg_apply_path(options()$act.ffmpeg.command.images)
					inputargs <- if (isTRUE(videoFastPositioning)) {
						sprintf('-ignore_editlist 1 -avoid_negative_ts make_zero -ss %s -i "INFILEPATH" -ss 10.000', as.character(pmax(0, stills.values - 10)))
					} else {
						sprintf('-ignore_editlist 1 -avoid_negative_ts make_zero -i "INFILEPATH" -ss %s', as.character(stills.values))
					}
					cmd <- vapply(seq_along(inputargs), function(k) {
						c1 <- stringi::stri_replace_all_fixed(cmd, "INPUTARGS",   inputargs[k])
						c1 <- stringi::stri_replace_all_fixed(c1,  "OUTFILEPATH", out_filePaths[k])
						c1
					}, character(1))
					cmd <- stringr::str_flatten(cmd, collapse='\n')
					win_cmd <- stringi::stri_replace_all_fixed(cmd, "INFILEPATH", "%PATH_INPUT%")
					mac_cmd <- stringi::stri_replace_all_fixed(cmd, "INFILEPATH", "$PATH_INPUT")
					
					#windows version stills
					#(flatten/ some replacements windows )
					win_info         <- c()
					win_cmd          <- stringr::str_replace_all(win_cmd, "/", "\\\\")
					win_makedir      <- sprintf('IF NOT EXIST "%s" ( md "%s" )', out_folder_stills, out_folder_stills)
					win_makedir      <- stringr::str_replace_all(win_makedir, "/", "\\\\")
					win_if_statement <-"\nIF EXIST \"%1$s\" (\n %2$s\n %3$s\n)\n"
					win_if_statement <- sprintf(win_if_statement, "%PATH_INPUT%", win_makedir, win_cmd)
					win_stills       <- c(win_info, win_if_statement)
					
					#mac version stills
					mac_info         <- c("#.... stills")
					mac_makedir      <- sprintf('mkdir -p "%s"', out_folder_stills)
					mac_if_statement <- "\nif [ -f \"%1$s\" ]\nthen\n %2$s\n %3$s\nfi\n"
					mac_if_statement <- sprintf(mac_if_statement, "$PATH_INPUT", mac_makedir ,mac_cmd)
					mac_stills       <- c(mac_info, mac_if_statement)
					
					#---- . command add ----
					#to search
					s@results[res, "cuts.stills.mac"] <- stringr::str_flatten(mac_stills, collapse="\n")
					s@results[res, "cuts.stills.win"] <- stringr::str_flatten(win_stills, collapse="\n")
					
					#to total cutlist
					mac_cutlist <- c(mac_cutlist, mac_stills)
					win_cutlist <- c(win_cutlist, win_stills)
				}	
			}
		}
	}
	
	#==== SAVE entire cut list to search object ====
	s@cuts.cutlist.win <- stringr::str_flatten(win_cutlist, collapse="\n")
	s@cuts.cutlist.mac <- stringr::str_flatten(mac_cutlist, collapse="\n")
	if (length(win_cutlist)==0) {
		w <- unique(myWarnings)
		cli::cli_abort(c("No cut list created.", stats::setNames(w, rep("-", length(w)))))
	} 
	
	#==== SAVE to file ====
	# if output folder is given
	if (!is.null(folderOutput)) {
		#-- file name
		helper_cutlist_save(cutlistMac  = if ("mac" %in% outputOS) mac_cutlist else NULL, 
							cutlistWin  = if ("win" %in% outputOS) win_cutlist else NULL, 
							outFolder   = file.path(out_folder_main, s@name), 
							outFilename = outputFileName)
	}
	
	#=== print warnings
	if (length(myWarnings) > 0) {
		w <- unique(myWarnings)
		cli::cli_warn(c("{length(w)} transcript(s) not found in corpus:", stats::setNames(w, rep("-", length(w)))))
	}
	
	#=== return
	return(s)
}

#==== FUNCTIONS ====

# Replace the leading literal "ffmpeg" of a command template with the
# executable set in option act.path.ffmpeg (quoted). When the option is
# empty the template stays as is, so the machine that later RUNS the cut
# list resolves ffmpeg via its own PATH (cut lists may be executed on a
# different machine than the one that generated them).
.ffmpeg_apply_path <- function(cmd) {
	ffmpeg_path <- getOption("act.path.ffmpeg", "")
	if (!is.null(ffmpeg_path) && length(ffmpeg_path) == 1 && nzchar(ffmpeg_path)) {
		starts <- stringr::str_starts(cmd, stringr::fixed("ffmpeg "))
		cmd[starts] <- paste0('"', ffmpeg_path, '"', stringr::str_sub(cmd[starts], 7L))
	}
	cmd
}

makeVideoBlock <- function(os, CreatePannedVersionsBlock, in_filePath, out_filename, cmd, cmd_titletext) {
	#if (os=="win") {
	#	block <- "\nIF EXIST \"INFILEPATH\" ( \n title \"cmd_titletext\"\n FFMPEGcmd1\n FFMPEGcmd2\n FFMPEGcmd3\n)\n\n"
	#} else {
	#	block <- "\nif [ -f \"INFILEPATH\" ]\nthen\n FFMPEGcmd1\n FFMPEGcmd2\n FFMPEGcmd3\nfi\n\n"
	#}
	if (os=="win") {
		block <- "\nIF EXIST \"%PATH_INPUT%\" ( \n title \"cmd_titletext\"\n FFMPEGcmd1\n FFMPEGcmd2\n FFMPEGcmd3\n)\n\n"
	} else {
		block <- "\nif [ -f \"$PATH_INPUT\" ]\nthen\n FFMPEGcmd1\n FFMPEGcmd2\n FFMPEGcmd3\nfi\n\n"
	}
	
	block <- stringr::str_replace_all(block, "cmd_titletext", cmd_titletext)
	block <- stringr::str_replace_all(block, "OUTFILENAME", out_filename)
	block <- stringr::str_replace_all(block, "INFILEPATH", in_filePath)
	
	#0 only all audio
	#1 ch1
	#2 ch2
	#3 ch1 & 2
	#4 all audio & ch1 & ch2
	if (CreatePannedVersionsBlock==0) { 
		block <- 	stringr::str_replace_all(block, "FFMPEGcmd1", cmd[1])
		block <- 	stringr::str_replace_all(block, " *FFMPEGcmd2\n", "" )
		block <- 	stringr::str_replace_all(block, " *FFMPEGcmd3\n", "")
	}
	
	if (CreatePannedVersionsBlock==1) { 
		block <- 	stringr::str_replace_all(block, " *FFMPEGcmd1\n", "")
		block <- 	stringr::str_replace_all(block, "FFMPEGcmd2", cmd[2])
		block <- 	stringr::str_replace_all(block, " *FFMPEGcmd3\n", "")
	}
	
	if (CreatePannedVersionsBlock==2) { 
		block <- 	stringr::str_replace_all(block, " *FFMPEGcmd1\n", "")
		block <- 	stringr::str_replace_all(block, " *FFMPEGcmd2\n", "")
		block <- 	stringr::str_replace_all(block, "FFMPEGcmd3", cmd[3])
	}
	
	if (CreatePannedVersionsBlock==3) { 
		block <- 	stringr::str_replace_all(block, " *FFMPEGcmd1\n", "")
		block <- 	stringr::str_replace_all(block, "FFMPEGcmd2", cmd[2])
		block <- 	stringr::str_replace_all(block, "FFMPEGcmd3", cmd[3])
	}
	
	if (CreatePannedVersionsBlock==4) { 
		block <- 	stringr::str_replace_all(block, "FFMPEGcmd1", cmd[1])
		block <- 	stringr::str_replace_all(block, "FFMPEGcmd2", cmd[2])
		block <- 	stringr::str_replace_all(block, "FFMPEGcmd3", cmd[3])
	}
	
	return (block)
}

# Build the OPTIONS replacement string for one panning version.
# pan: NULL or a pan filter string e.g. "pan=1c|c0=c0"
# loudnorm: NULL or the loudnorm filter string from act.ffmpeg.audio.loudnorm
# cv: "" or "-c:v copy"
# Returns a string with leading and trailing space (or just " " when empty).
.search_cuts_build_options <- function(pan, loudnorm, cv) {
	af_parts <- character(0)
	if (!is.null(pan)      && nzchar(pan))      af_parts <- c(af_parts, pan)
	if (!is.null(loudnorm) && nzchar(loudnorm)) af_parts <- c(af_parts, loudnorm)
	af_str <- if (length(af_parts) > 0) sprintf('-af "%s"', paste(af_parts, collapse = ",")) else ""
	opts   <- stringr::str_trim(paste(c(af_str, cv)[nzchar(c(af_str, cv))], collapse = " "))
	if (nzchar(opts)) paste0(" ", opts, " ") else " "
}
